config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :ebooks
  root "home#index"
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/ebook.rb
# frozen_string_literal: true

class Ebook < ApplicationRecord
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/ebooks_controller.rb
# frozen_string_literal: true

class EbooksController < ApplicationController
  before_action :set_ebook, only: %i[show edit update destroy]

  # GET /ebooks or /ebooks.json
  def index
    @ebooks = Ebook.page(params[:page]).per(5)
  end

  # GET /ebooks/1 or /ebooks/1.json
  def show; end

  # GET /ebooks/new
  def new
    @ebook = Ebook.new
  end

  # GET /ebooks/1/edit
  def edit; end

  # POST /ebooks or /ebooks.json
  def create
    @ebook = Ebook.new(ebook_params)

    respond_to do |format|
      if @ebook.save
        format.html { redirect_to ebook_url(@ebook), notice: "Ebook was successfully created." }
        format.json { render :show, status: :created, location: @ebook }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ebooks/1 or /ebooks/1.json
  def update
    respond_to do |format|
      if @ebook.update(ebook_params)
        format.html { redirect_to ebook_url(@ebook), notice: "Ebook was successfully updated." }
        format.json { render :show, status: :ok, location: @ebook }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ebook.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ebooks/1 or /ebooks/1.json
  def destroy
    @ebook.destroy!

    respond_to do |format|
      format.html { redirect_to ebooks_url, notice: "Ebook was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_ebook
    @ebook = Ebook.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def ebook_params
    params.require(:ebook).permit(:title, :description, :author, :genre, :isbn, :price)
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/ebooks/_ebook.html.erb
<div id="<%= dom_id ebook %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= ebook.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Description:</strong>
    <%= ebook.description %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Author:</strong>
    <%= ebook.author %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Genre:</strong>
    <%= ebook.genre %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Isbn:</strong>
    <%= ebook.isbn %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Price:</strong>
    <%= ebook.price %>
  </p>
</div>

app/views/ebooks/_form.html.erb
<%= form_with(model: ebook, class: "contents mx-auto md:w-auto") do |form| %>
  <% if ebook.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(ebook.errors.count, "error") %> prohibited this ebook from being saved:</h2>

      <ul>
        <% ebook.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 4, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :author %>
    <%= form.text_field :author, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :genre %>
    <%= form.text_field :genre, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :isbn %>
    <%= form.text_field :isbn, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :price %>
    <%= form.text_field :price, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800" %>
  </div>
<% end %>

app/views/ebooks/edit.html.erb
<div class="mx-auto md:w-auto w-full">
  <h1 class="font-bold text-4xl">Editing ebook</h1>

  <%= render "form", ebook: @ebook %>

  <%= link_to "Show this ebook", @ebook, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
  <%= link_to "Back to ebooks", ebooks_path, class: "text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" %>
</div>

app/views/ebooks/index.html.erb
<div class="w-full">
  <% content_for :title, "Ebooks" %>

  <div class="flex justify-between items-center mb-6">
    <h1 class="font-bold text-2xl">Ebooks</h1>
    <%= link_to "New ebook", new_ebook_path, class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
  </div>

  <div class="relative overflow-x-auto">
    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400 border border-gray-300">
      <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400 border-gray-200">
      <tr>
        <th scope="col" class="px-6 py-3">ID</th>
        <th scope="col" class="px-6 py-3">Title</th>
        <th scope="col" class="px-6 py-3">Author</th>
        <th scope="col" class="px-6 py-3">Genre</th>
        <th scope="col" class="px-6 py-3">Price</th>
        <th scope="col" class="px-6 py-3">Actions</th>
      </tr>
      </thead>
      <tbody>
      <% @ebooks.each do |ebook| %>
        <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
          <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
            <%= ebook.id %>
          </th>
          <td class="px-6 py-4"><%= ebook.title %></td>
          <td class="px-6 py-4"><%= ebook.author %></td>
          <td class="px-6 py-4"><%= ebook.genre %></td>
          <td class="px-6 py-4"><%= ebook.price %></td>
          <td class="px-6 py-4">
            <%= link_to "Show", ebook_path(ebook), class: "text-indigo-600 hover:text-indigo-900" %> |
            <%= link_to "Edit", edit_ebook_path(ebook), class: "text-indigo-600 hover:text-indigo-900" %> |
            <%= link_to "Delete", ebook_path(ebook), data: {turbo_method: "delete", turbo_confirm: "Are you sure?" }, class: "text-red-600 hover:text-red-900" %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>

    <div class="mt-1">
      <%= paginate @ebooks %>
    </div>
  </div>
</div>

app/views/ebooks/new.html.erb
<div class="mx-auto md:w-auto w-full">
  <h1 class="font-bold text-4xl">New ebook</h1>

  <%= render "form", ebook: @ebook %>

  <%= link_to "Back to ebooks", ebooks_path, class: "text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" %>
</div>

app/views/ebooks/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @ebook %>

    <%= link_to "Edit this ebook", edit_ebook_path(@ebook), class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" %>
    <%= link_to "Back to ebooks", ebooks_path, class: "text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this ebook", @ebook, method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 me-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Home#index</h1>
  <p>Find me in app/views/home/index.html.erb</p>
</div>

app/views/layouts/_navbar.html.erb
<nav class="bg-gray-100 border-gray-200 dark:bg-gray-900">
  <div class="flex flex-wrap justify-between items-center mx-auto max-w-screen-xl p-4">
    <a href="#" class="flex items-center space-x-3 rtl:space-x-reverse">
      <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Ebook Hub</span>
    </a>
    <div class="flex items-center space-x-6 rtl:space-x-reverse">
      <ul class="flex flex-row font-medium mt-0 space-x-8 rtl:space-x-reverse text-sm">
        <li class="text-sm  text-gray-500 dark:text-white hover:underline">
          user@mail.com
        </li>
        <li>
          <%= link_to 'Edit Profile', "#", class: "text-sm  text-blue-600 dark:text-blue-500 hover:underline" %>
        </li>
        <li>
          <%= link_to 'Logout', "#", data: { turbo_method: :delete }, class: "text-sm  text-blue-600 dark:text-blue-500 hover:underline" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<nav class="bg-gray-100 border-gray-200 dark:bg-gray-900">
  <div class="max-w-screen-xl px-4 py-3 mx-auto">
    <div class="flex items-center">
      <ul class="flex flex-row font-medium mt-0 space-x-8 rtl:space-x-reverse text-sm">
        <li>
          <%= link_to "Home", root_path, class: "block py-2 px-3 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white md:dark:text-blue-500" %>
        </li>
        <li>
          <%= link_to "Ebooks", ebooks_path, class: "block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:border-0 md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent" %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLearningBase</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-100">
    <div>
      <%= render "layouts/navbar" %>
    </div>
    <main class="container mx-auto mt-16 px-5 flex max-w-screen-xl">
      <%= yield %>
    </main>
  </body>
</html>